### ISSUE TITLE
rar file broken?

### ISSUE THREAD

**Issue by TSHAWDS** [eternalfrenzy/discord-animated-status#2]
Hello,
it seems I can't get this to work. When I download the main.rar it tells me "the archive is either in unknown format or damaged"
Am I just to stupid or is it really damaged?
Please tell me how to fix this.

**Comment by eternalfrenzy** [comment]
nope, not damaged. make sure you download the latest release archive and extract it with either 7zip or winrar

**Comment by TSHAWDS** [comment]
It works with 7zip but no luck with winrar.
But I got it now, thank you for your help.
