### ISSUE TITLE
Emojis are not working.

### ISSUE THREAD

**Issue by maxw2000** [eternalfrenzy/discord-animated-status#3]
Hello,

I have a issue when I copy the emoji it will show up weird and will not show inside Discord.
![image](https://user-images.githubusercontent.com/22998325/81324915-f26e5580-9097-11ea-8f1a-3fe1f07b1356.png)

Thank you for making this program.

Have a good day!
~ MVDW

**Comment by eternalfrenzy** [comment]
which OS are you using? this may occur because win7 by default doesn't support half of the unicode characters including emojis. if you're using win7, try installing this update: https://www.microsoft.com/ru-ru/download/details.aspx?id=30566
