### ISSUE TITLE
Пофиксите уже эту херню

### ISSUE THREAD

**Issue by TheFaser** [eternalfrenzy/discord-animated-status#7]
я, как великий осознанный потребитель кала, хочу вам сказать, что я нуждаюсь в фиксе проблемы. при запуске винды, ты посасываешь у вашего приложения, потому что дискорд не запущен, а прога запущена и приходится перезапускать прогу

**Comment by RinkLinky** [comment]
already fixed.

**Comment by Risondy** [comment]
Фасер, хватит со своей постиронией! я понимаю что ты ярый фанат хауди хо и течешь по нему и из за этого ты хейтишь шимуса, но хватит использовать постиронию иначе я позвоню твоей маме и скажу все! И еще, делай уроки, тебе завтра в школу.
